### ISSUE TITLE
Add tests and documentation for file handling changes

### ISSUE THREAD

**Issue by thienlnam** [Expensify/react-native-onyx#112]
Follow up to PR: https://github.com/Expensify/react-native-onyx/pull/102

1. Write tests verifying that the different providers work as expected and produce the expected result (Discussion https://github.com/Expensify/react-native-onyx/pull/102#discussion_r741375587)

2. Add some documentation indicating this under the hood change

cc @kidroca

**Comment by kidroca** [comment]
Feel free to assign me here, I'll proceed with this when I have the chance

**Comment by kidroca** [comment]
PR Ready: #113

**Comment by thienlnam** [comment]
Sweet, thanks!
