### ISSUE TITLE
Make Onyx values update instantly

### ISSUE THREAD

**Issue by roryabraham** [Expensify/react-native-onyx#123]
Coming from: https://github.com/Expensify/App/pull/8306#discussion_r834773616

### Problem
Setting values in Onyx always takes at least one tick of the event loop and updates subscribers late.

### Why this is important
A lot of our code could be made simpler and easier to reason about if we could safely assume that any value written in Onyx will be updated immediately.

### Solution
Need to explore a bit, but probably an in-memory cache of some kind. Also need to be careful not to break stuff and to update all our tests appropriately.

**Comment by marcaaron** [comment]
We have an in memory cache already and force the extra tick because `keyChanged()` used to happen after a call to `AsyncStorage.getItem()` (or something like that).

https://github.com/Expensify/react-native-onyx/blob/2d42566779884bb445aa59dd48b5bcdff6c0a4e6/lib/Onyx.js#L550-L551

**Comment by roryabraham** [comment]
I do think this behavior is a bit confusing, but it's not a priority and I'm not going to work on this any time soon. Going to just close this for now
