### ISSUE TITLE
[Feat] Add a configuration option to unsubscribe for some keys for StorageEvent across tabs

### ISSUE THREAD

**Issue by mdneyazahmad** [Expensify/react-native-onyx#127]
## Problem
When user opens multiple tabs with different reports. We do not want some data in `onyx` to sync across tabs. 

### Proposed Solution
We will add a property `keysToDisableSyncEvents` an array with keys on configuration object for `Onyx.init`. It will prevent syncing for these keys when `StorageEvent` is fired. 

suggested by: @marcaaron 

comming from pr https://github.com/Expensify/App/pull/8227

**Comment by Beamanator** [comment]
Note: The exact comment when this was suggested is here: https://github.com/Expensify/App/pull/8227#discussion_r845652187

**Comment by mdneyazahmad** [comment]
@Beamanator We should close this issue as related issue on Expensify/App is fixed and closed.

**Comment by Beamanator** [comment]
Agreed 👍
