### ISSUE TITLE
Prepare react-native-onyx for TypeScript migration

### ISSUE THREAD

**Issue by hayata-suenaga** [Expensify/react-native-onyx#260]
Part of [the TypeScript migration](https://github.com/Expensify/App/issues/16665) issues.

- [Design doc](https://docs.google.com/document/d/1LNcgYeYyovQ88gNjLIgBqBReLtbLAbxeAbna9QKxeAQ/edit#bookmark=id.f26etjel5h0v)
- Remove `expensify-common` package.
  - Copy methods imported from `expensify-commmon`. There are only two functions imported. ([Stack discussion](https://expensify.slack.com/archives/C0593T50UHG/p1684971334416899?thread_ts=1684958481.278379&cid=C0593T50UHG))
- Create type definition files for exported APIs

**Comment by neil-marcellini** [comment]
I'm also assigning to get credit for all the time I put into the review.

**Comment by hayata-suenaga** [comment]
[The PR](https://github.com/Expensify/react-native-onyx/pull/267) for creating type declaration files are merged and Onyx is ready to be used in App for migration. Closing this 🥳
