### ISSUE TITLE
Onyx.merge('key', null) breaks subsequent merges for 'key'

### ISSUE THREAD

**Issue by arosiclair** [Expensify/react-native-onyx#425]
[Codesandbox example](https://codesandbox.io/s/onyx-null-merge-problem-p6km8z?file=/src/App.js)

Rough steps:

1. Init onyx
2. Merge value on 'key'
3. Merge `null` on 'key'
4. Merge another value on 'key'
5. See that 'key' never updates

This is reproducible on the latest version (**v1.0.116**) and at least as early as **v1.0.100**

The root of the problem seems to be [here](https://github.com/Expensify/Comp/blob/db6da0cf126725486e4d8ab03872992ff12163f4/src/libs/actions/App.js#L36) where a `null` change removes the key from Onyx but never clears the `mergeQueue` for the key. Subsequent merges just continue filling the queue without ever getting processed.

cc @chrispader since you're on the blame

**Comment by arosiclair** [comment]
Looks like this was introduced in **v1.0.99** from [this PR](https://github.com/Expensify/react-native-onyx/pull/380/files). cc @tgolen @neil-marcellini

**Comment by tgolen** [comment]
Thanks for digging into this and finding a problem @arosiclair. Let's be sure to start off with writing a test that reproduces the bug. @chrispader can you please look into this?

**Comment by chrispader** [comment]
Yes, going to look into this either today or tomorrow! cc @arosiclair @tgolen

**Comment by chrispader** [comment]
@arosiclair @tgolen @neil-marcellini just created a [PR that fixes this issue and adds a new test](https://github.com/Expensify/react-native-onyx/pull/426) 👍

**Comment by arosiclair** [comment]
Just merged it thanks for putting a fix out quickly!

**Comment by arosiclair** [comment]
@chrispader can you also post a PR to bump our version of Onyx in NewDot?

**Comment by chrispader** [comment]
> @chrispader can you also post a PR to bump our version of Onyx in NewDot?

yes, will do 👍

**Comment by arosiclair** [comment]
This is all set!
