### ISSUE TITLE
More improvements for `Onyx.connect` (After cache)

### ISSUE THREAD

**Issue by kidroca** [Expensify/react-native-onyx#78]
There are some more improvements that can be done to the `connect` function specifically for storage accessing

### 1. Improvements regarding the `getAllKeys` usage in `connect`

https://github.com/Expensify/react-native-onyx/blob/27c0ba8ba1dee20171062ff249d03f2696d078a8/lib/Onyx.js#L373-L382

It serves to distinct any collection keys when connecting to a collection - something that ATM is not possible without first retrieving all storage keys
*The above wasn't easy to tell by the code itself, I only find out when debugging*

So we only need `getAllKeys` when we're dealing with a collection to get a list of collection item keys - `matchingKeys`
Otherwise we're always connecting to a single key - `mapping.key` 

##### An oversimplified example
```js
let matchingKeys = [mapping.key];
if (isCollectionKey(mapping.key)) {
  const allKeys = await getAllKeys();
  matchingKeys = _.filter(allKeys, key => isKeyMatch(mapping.key, key));
}
```

### 2. Values can be retrieved using `multiGet`
We already have a list of keys and we can use `multiGet` instead of retrieving each key separately

https://github.com/Expensify/react-native-onyx/blob/27c0ba8ba1dee20171062ff249d03f2696d078a8/lib/Onyx.js#L389-L401

This can instead be:

```js
// Result is like: [['k1', 'val1'], ['k2', 'val2']]
const retrievedKeyValuePairs = await multiGet(matchingKeys);
  
if (mapping.withOnyxInstance && isCollectionKey(mapping.key)) {
  const asCollection = _.object(retrievedKeyValuePairs); // see https://underscorejs.org/#object
  sendDataToConnection(mapping, asCollection));
}
else {
  _.each(retrievedKeyValuePairs, ([key, val]) => sendDataToConnection(mapping, val, key));
}
```

Currently there's no `multiGet` definition in Onyx, but we can add one and hook it to cache as well.
It can check if any of the keys are available in cache and only call [`AsyncStorage.multiGet`](https://reactnative.dev/docs/asyncstorage#multiget) with the remaining, then cache each key/val from the result

As we've seen from previous benchmarks: https://github.com/Expensify/Expensify.cash/issues/2762#issuecomment-848318315 retriving multiple items in parallel even with cache is flooding the bridge with calls (when data is not available in cache e.g. startup)

**Comment by kidroca** [comment]
#### Onyx.connect called for a collection
![image](https://user-images.githubusercontent.com/12156624/120631429-8c0d5f80-c470-11eb-9c59-b1c2d968cc36.png)

#### Onyx.connect called for a single item
![image](https://user-images.githubusercontent.com/12156624/120631697-d2fb5500-c470-11eb-88f7-ba9a10ad2f76.png)

**Comment by quinthar** [comment]
Very cool!  I love this!

**Comment by marcaaron** [comment]
@kidroca should we maybe break these 2 issues up into individual issues to focus on in isolation? 
Also, is "Values can be retrieved using multiGet" somehow different from "[Optimization] Easy Onyx.get batching"?

**Comment by kidroca** [comment]
> @kidroca should we maybe break these 2 issues up into individual issues to focus on in isolation?

The first part of the ticket might not be necessary, the result of `getAllKeys` comes from cache ever since the first usage so it works quick

> Also, is "Values can be retrieved using multiGet" somehow different from "[Optimization] Easy Onyx.get batching"?

Hmm yeah they are similar, but the idea here is to use `multiGet` since we have a list of items `matchingKeys`. While the other ticket #84 proposes to use `multiGet` for every `get` (e.g. the once happening internally as well) because `AsyncStorage.multiGet` would batch keys with `setImmediate`

We can probably close this ticket and keep the newer one

**Comment by marcaaron** [comment]
Alright sounds good. I'm going to close up this issue then. It would be great if we can pull out some of these observations and focus on each one in isolation. I'm trying to help funnel these ideas into actionable steps but having issues like "optimize x" and "improve y" make it pretty tricky to tell what is what.

**Comment by marcaaron** [comment]
Also, let's move these issue into `Expensify.cash` please so they can get more attention :)
